### ISSUE TITLE
How to use ng2-pagination with angular2 Final 2.0.0?

### ISSUE THREAD

**Issue by sanket360** [michaelbromley/ng2-pagination#120]
Hi

I am trying use ng2-pagination with angular2 Final 2.0.0 version but getting error-

```
Error: TypeError: ctorParameters.map is not a function
	    at ReflectionCapabilities.parameters (https://npmcdn.com/@angular/core@2.0.0/src/reflection/reflection_capabilities.js!transpiled:79:59)
	    at Reflector.parameters (https://npmcdn.com/@angular/core@2.0.0/src/reflection/reflector.js!transpiled:111:60)
	    at CompileMetadataResolver.getDependenciesMetadata (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:553:98)
	    at CompileMetadataResolver.getTypeMetadata (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:514:38)
	    at CompileMetadataResolver.getPipeMetadata (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:542:40)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:353:67)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:343:56)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0/src/metadata_resolver.js!transpiled:331:62)
	    at Array.forEach (native)
	Error loading http://run.plnkr.co/preview/ciylef2540007375phw4o0ocq/src/main.ts
```

Sample plunker available here - http://embed.plnkr.co/RvxmTxyODU6VFQCoDZLN/

Can anyone please help me on this?

**Comment by sanket360** [comment]
I also tried simple quick-start approach but getting above mentioned error

Steps performed in this approach are-
1. Download angular2 quickstart sample of version Final 2.0.0
2. Added ng2-pagination using - `npm install ng2-pagination --save`
3. Updated systemjs.config.js with this line - `'ng2-pagination':             { main: './dist/ng2-pagination.js', defaultExtension: 'js' }`
4. Using simple example from this link - http://michaelbromley.github.io/ng2-pagination/#/

**Comment by michaelbromley** [comment]
Hi, 

From the readme:

> This library is built to work with Angular 2.3.0+

From the changelog of v2.0.0:

> The module is being built with Angular 2.4.3. Therefore the metadata output is not compatible with Angular < 2.3.0. Attempting to use this version in an app running Angular < 2.3.0 will result in a "ctorParameters.map is not a function" error. 

Solution:

Use v1.0.1 until you are able to update to a newer version of Angular.
